# EDIT this workflow name
name: Webhook

on:
  # Trigger the workflow on push or pull request merge to the master branch
  push:
    branches: [ master ]

jobs:

  trigger_hook:
    runs-on: ubuntu-latest

    steps:
    - name: Webhook
      run: |
        # EDIT this URL
        URL="https://xitizu.com/docs/webhook"
        echo "Webhook sending to $URL ..."
        SECRET=$(echo "${{ secrets.WEBHOOKSECRET }}")
        curl --request POST --data \
        "{\"repository\": \"${{ github.event.repository.full_name }}\", \"secret\": \"$SECRET\"}" \
        $URL
